### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by zbohler** [DevMiser/Lumina#11]
I get the following when I run the program from the terminal window. Any thoughts?

Traceback (most recent call last):
  File "/home/pi/Lumina/Lumina.py", line 75, in <module>
    root = tk.Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by DevMiser** [comment]
It looks like Tkinter cannot find the necessary display information.  Try setting a display environment by entering the following in the terminal window before running the program from the terminal window:
export DISPLAY=:0.0

**Comment by zbohler** [comment]
That appears to have resolved the issue. Thank you!
